/* 0024_email_notifications.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.order_items add column if not exists reminder_sent_at timestamptz;
comment on column public.order_items.reminder_sent_at is 'When we warned them the review window was closing. Null means we have not.';
create table if not exists public.email_log ( id uuid primary key default gen_random_uuid(), template text not null, to_address text not null, subject text not null, order_id uuid references public.orders (id) on delete set null, order_item_id uuid references public.order_items (id) on delete set null, sent_at timestamptz not null default timezone('utc', now()), provider_id text, error text );
comment on table public.email_log is 'Every message we sent, and every one we failed to. Internal - no customer policy exists.';
create index if not exists email_log_sent_idx on public.email_log (sent_at desc);
create index if not exists email_log_item_idx on public.email_log (order_item_id, template);
alter table public.email_log enable row level security;
do $$ begin create policy "Admins read the email log" on public.email_log for all using (public.is_admin()) with check (public.is_admin()); exception when duplicate_object then null; end; $$;
alter table public.settings add column if not exists approval_reminder_days smallint not null default 3 check (approval_reminder_days >= 0);
