/* 0028_rate_card_worklist.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.inbound_emails add column if not exists rate_card_dismissed_at timestamptz;
alter table public.inbound_emails add column if not exists rate_card_added_at timestamptz;
alter table public.inbound_emails add column if not exists rate_card_added_by text;
comment on column public.inbound_emails.rate_card_added_at is 'When a human pasted rate card contents into this email. The prices after that point were typed by a person, not read from the reply.';
create index if not exists inbound_emails_rate_card_idx on public.inbound_emails (status, rate_card_dismissed_at) where status = 'ignored';
