/* 0029_no_draft_worklist.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
do $$ begin if exists ( select 1 from information_schema.columns where table_schema = 'public' and table_name = 'inbound_emails' and column_name = 'rate_card_dismissed_at' ) and not exists ( select 1 from information_schema.columns where table_schema = 'public' and table_name = 'inbound_emails' and column_name = 'no_draft_dismissed_at' ) then alter table public.inbound_emails rename column rate_card_dismissed_at to no_draft_dismissed_at; end if; end; $$;
alter table public.inbound_emails add column if not exists no_draft_dismissed_at timestamptz;
alter table public.inbound_emails add column if not exists no_draft_handled_at timestamptz;
alter table public.inbound_emails add column if not exists no_draft_handled_by text;
comment on column public.inbound_emails.no_draft_handled_at is 'When an admin added this publisher to the marketplace by hand after reading the reply themselves. Not the same as dismissed, which means there was nothing worth having.';
comment on column public.inbound_emails.no_draft_dismissed_at is 'When an admin decided this reply was not worth acting on. It leaves the worklist and does not come back.';
drop index if exists public.inbound_emails_rate_card_idx;
create index if not exists inbound_emails_no_draft_idx on public.inbound_emails (status, no_draft_dismissed_at, no_draft_handled_at) where status = 'ignored';
