/* 0030_nightly_import.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.sourcing_settings add column if not exists nightly_import_enabled boolean not null default false;
alter table public.sourcing_settings add column if not exists nightly_import_query text not null default '-from:me newer_than:14d (price OR rates OR "guest post" OR sponsored OR advertising)';
alter table public.sourcing_settings add column if not exists nightly_import_cap integer not null default 200 check (nightly_import_cap > 0 and nightly_import_cap <= 2000);
alter table public.sourcing_settings add column if not exists nightly_import_reads boolean not null default false;
alter table public.sourcing_settings add column if not exists nightly_import_last_run_at timestamptz;
alter table public.sourcing_settings add column if not exists nightly_import_last_result text;
comment on column public.sourcing_settings.nightly_import_reads is 'Off by default. When on, the nightly import also sends what it found to the model, within the monthly budget.';
comment on column public.sourcing_settings.nightly_import_last_result is 'What the last scheduled run did, in words, so a schedule that quietly stopped working is visible without reading logs.';
