/* 0033_majestic_metrics.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.websites add column if not exists trust_flow smallint, add column if not exists citation_flow smallint;
alter table public.websites add column if not exists majestic_updated_at timestamptz;
comment on column public.websites.trust_flow is 'Majestic Trust Flow, 0-100. Null means nobody has measured it, which is not the same as zero.';
comment on column public.websites.citation_flow is 'Majestic Citation Flow, 0-100. Null means nobody has measured it.';
comment on column public.websites.majestic_updated_at is 'When a Majestic export last wrote to this listing, so a stale figure can be spotted.';
create index if not exists websites_trust_flow_idx on public.websites (trust_flow desc) where trust_flow is not null;
create table if not exists public.website_topics ( website_id uuid not null references public.websites (id) on delete cascade, position smallint not null check (position between 0 and 2), topic text not null, value smallint not null default 0, updated_at timestamptz not null default timezone('utc', now()), primary key (website_id, position) );
comment on table public.website_topics is 'Majestic Topical Trust Flow: what links to a site, strongest first. Evidence shown to buyers, never a category.';
alter table public.website_topics enable row level security;
do $$ begin create policy "Anyone can read website topics" on public.website_topics for select using (true); exception when duplicate_object then null; end; $$;
do $$ begin create policy "Admins manage website topics" on public.website_topics for all using (public.is_admin()) with check (public.is_admin()); exception when duplicate_object then null; end; $$;
do $$ begin create trigger website_topics_set_updated_at before update on public.website_topics for each row execute function public.set_updated_at(); exception when duplicate_object then null; end; $$;
insert into public.categories (slug, name, description, position, featured) values ('news-media', 'News & Media', 'Newspapers, magazines, broadcasters and the media industry.', 14, false), ('science-environment', 'Science & Environment', 'Research, climate, energy, agriculture and the natural world.', 15, false), ('education', 'Education & Reference', 'Schools, universities, courses, libraries and archives.', 16, false) on conflict (slug) do nothing;
