/* 0034_refresh_progress.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.refresh_runs add column if not exists domains_total integer;
comment on column public.refresh_runs.domains_total is 'How many domains this run set out to refresh, so progress has a denominator. Null on runs recorded before it was tracked.';
