/* 0035_blog_sections.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.posts add column if not exists body_doc jsonb, add column if not exists sections jsonb not null default '{}'::jsonb;
comment on column public.posts.body_doc is 'Rich text document from the editor. Null means the markdown in body is the article.';
comment on column public.posts.sections is 'Marketplace block, FAQs, related mode and closing CTA. Empty uses the defaults in code.';
