/* 0038_page_template.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.custom_pages add column if not exists template text not null default 'service';
alter table public.custom_pages drop constraint if exists custom_pages_template_known;
alter table public.custom_pages add constraint custom_pages_template_known check (template in ('service', 'niche'));
comment on column public.custom_pages.template is 'Which frontend template draws this page: service, or niche. The application owns the list; this is the backstop.';
