/* 0040_section_style_and_artwork.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.page_sections add column if not exists style jsonb not null default '{}'::jsonb;
alter table public.page_sections drop constraint if exists page_sections_style_object;
alter table public.page_sections add constraint page_sections_style_object check (jsonb_typeof(style) = 'object');
alter table public.global_sections add column if not exists style jsonb not null default '{}'::jsonb;
alter table public.global_sections drop constraint if exists global_sections_style_object;
alter table public.global_sections add constraint global_sections_style_object check (jsonb_typeof(style) = 'object');
comment on column public.page_sections.style is 'Named choices from the CMS palette - background, text tone, accent, decoration, artwork placement. Never a colour value.';
alter table public.media_assets add column if not exists artwork_name text, add column if not exists artwork_category text, add column if not exists artwork_slug text, add column if not exists description text not null default '', add column if not exists placement text not null default '', add column if not exists aspect text not null default '', add column if not exists active boolean not null default true;
alter table public.media_assets drop constraint if exists media_assets_artwork_category;
alter table public.media_assets add constraint media_assets_artwork_category check ( artwork_category is null or artwork_category in ('general', 'seo', 'niche', 'content', 'support', 'decoration') );
alter table public.media_assets drop constraint if exists media_assets_artwork_name_length;
alter table public.media_assets add constraint media_assets_artwork_name_length check ( artwork_name is null or char_length(artwork_name) between 1 and 80 );
create unique index if not exists media_assets_artwork_slug_idx on public.media_assets (artwork_slug) where artwork_slug is not null;
create index if not exists media_assets_artwork_idx on public.media_assets (artwork_category, created_at desc) where artwork_category is not null;
comment on column public.media_assets.artwork_slug is 'Stable name a section points at, so replacing the file updates every page using it.';
