/* 0041_section_drafts.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.page_sections add column if not exists draft jsonb;
alter table public.page_sections drop constraint if exists page_sections_draft_object;
alter table public.page_sections add constraint page_sections_draft_object check ( draft is null or jsonb_typeof(draft) = 'object' );
create index if not exists page_sections_draft_idx on public.page_sections (page_slug) where draft is not null;
comment on column public.page_sections.draft is 'A pending edit an administrator has previewed but not published. Null normally. Never selected by the public read.';
