/* 0044_country_source.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.websites add column if not exists country_source text;
alter table public.websites drop constraint if exists websites_country_source_check;
alter table public.websites drop constraint if exists websites_country_needs_a_source;
update public.websites w set country_source = 'measured' where w.country_code is not null and w.country_source is null and jsonb_typeof(w.audience_split) = 'array' and jsonb_array_length(w.audience_split) > 0 and w.country_code = ( select upper(entry->>'country') from jsonb_array_elements(w.audience_split) as entry order by coalesce((entry->>'share')::numeric, 0) desc limit 1 );
update public.websites w set country_source = 'domain' where w.country_code is not null and w.country_source is null and ( lower(regexp_replace(w.domain, '^.*\.', '')) = lower(w.country_code) or (w.country_code = 'GB' and lower(regexp_replace(w.domain, '^.*\.', '')) = 'uk') );
update public.websites set country_source = 'default' where country_code = 'GB' and country_source is null and lower(regexp_replace(domain, '^.*\.', '')) <> 'uk' and not ( jsonb_typeof(audience_split) = 'array' and jsonb_array_length(audience_split) > 0 );
update public.websites set country_source = 'stated' where country_code is not null and country_source is null;
update public.websites set country_source = null where country_code is null and country_source is not null;
alter table public.websites add constraint websites_country_source_check check (country_source is null or country_source in ('stated', 'measured', 'domain', 'default'));
alter table public.websites add constraint websites_country_needs_a_source check ((country_code is null) = (country_source is null));
select coalesce(country_source, '(no country)') as source, count(*) as listings from public.websites group by 1 order by listings desc, source;
