/* 0050_organic_keywords.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
alter table public.websites add column if not exists organic_keywords integer check (organic_keywords is null or organic_keywords >= 0);
comment on column public.websites.organic_keywords is 'Keywords the site ranks for in the top 100 organic results, from the Ahrefs refresh. Null means never measured, which is not the same as zero.';
create index if not exists websites_organic_keywords_idx on public.websites (organic_keywords desc nulls last);
