/* 0055_gap_projects.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
create table if not exists public.gap_projects ( id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles (id) on delete cascade, name text not null, domain text not null, competitor_domains text[] not null default '{}', country char(2) not null default 'gb', last_run_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (user_id, domain) );
create index if not exists gap_projects_user_idx on public.gap_projects (user_id, updated_at desc);
comment on table public.gap_projects is 'A site a customer runs gap reports on - their own or a client''s. Readable and writable only by its owner.';
alter table public.gap_runs add column if not exists project_id uuid references public.gap_projects (id) on delete set null;
create index if not exists gap_runs_project_idx on public.gap_runs (project_id, created_at desc);
do $$ begin create trigger gap_projects_set_updated_at before update on public.gap_projects for each row execute function public.set_updated_at(); exception when duplicate_object then null; end; $$;
alter table public.gap_projects enable row level security;
do $$ begin create policy "Admins manage gap projects" on public.gap_projects for all using (public.is_admin()) with check (public.is_admin()); exception when duplicate_object then null; end; $$;
do $$ begin create policy "Customers manage their own gap projects" on public.gap_projects for all using (user_id = auth.uid()) with check (user_id = auth.uid()); exception when duplicate_object then null; end; $$;
alter table public.gap_lookups add column if not exists kind text not null default 'refdomains';
do $$ begin alter table public.gap_lookups add constraint gap_lookups_kind_known check (kind in ('refdomains', 'competitors')); exception when duplicate_object then null; end; $$;
create table if not exists public.competitor_suggestions ( domain text not null, country char(2) not null default 'gb', suggestions jsonb not null default '[]'::jsonb, units_charged integer not null default 0 check (units_charged >= 0), fetched_at timestamptz not null default timezone('utc', now()), primary key (domain, country) );
comment on table public.competitor_suggestions is 'Cached organic competitors per domain and market, with what the lookup cost. Admin-only: the customer sees the suggestions, not the bill.';
alter table public.competitor_suggestions enable row level security;
do $$ begin create policy "Admins manage competitor suggestions" on public.competitor_suggestions for all using (public.is_admin()) with check (public.is_admin()); exception when duplicate_object then null; end; $$;
