/* 0056_gap_sellable_needs_a_price.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
create or replace function public.gap_sellable(p_domains text[]) returns table (website_id uuid, domain text, domain_rating smallint, organic_traffic integer) language sql stable security definer set search_path = public as $$ select w.id, w.domain, w.domain_rating, w.organic_traffic from public.websites w where w.status = 'active' and w.domain = any (p_domains) and exists ( select 1 from public.services s where s.website_id = w.id and s.available and s.price_minor > 0 ); $$;
revoke all on function public.gap_sellable(text[]) from public;
revoke all on function public.gap_sellable(text[]) from anon;
revoke all on function public.gap_sellable(text[]) from authenticated;
