/* 0057_publisher_inbox_counts_in_sql.sql, flattened for the Supabase SQL editor. Generated by scripts/flatten-migration.mjs - do not edit this file, edit the migration and run the script again. One statement per line, no line comments, nothing to lose to a newline. The commentary lives in the migration itself. */
create index if not exists listing_drafts_open_domain_idx on public.listing_drafts (domain, id) where status in ('pending', 'approved');
create or replace function public.sourcing_contested_drafts() returns table ( draft_id uuid, domain text, status text, proposed jsonb, from_address text, sent_at timestamptz ) language sql stable security definer set search_path = public as $$ with contested as ( select d.domain from public.listing_drafts d where d.status in ('pending', 'approved') group by d.domain having count(*) > 1 ) select d.id, d.domain, d.status, d.proposed, e.from_address, e.sent_at from public.listing_drafts d join contested c on c.domain = d.domain left join public.inbound_emails e on e.id = d.email_id where d.status in ('pending', 'approved') order by d.domain asc, d.id asc; $$;
revoke all on function public.sourcing_contested_drafts() from public;
revoke all on function public.sourcing_contested_drafts() from anon;
revoke all on function public.sourcing_contested_drafts() from authenticated;
create or replace function public.sourcing_email_counts() returns table (status text, total bigint) language sql stable security definer set search_path = public as $$ select case when e.status = 'new' and e.batch_id is not null then 'in-flight' else e.status end, count(*) from public.inbound_emails e group by 1; $$;
revoke all on function public.sourcing_email_counts() from public;
revoke all on function public.sourcing_email_counts() from anon;
revoke all on function public.sourcing_email_counts() from authenticated;
